### ISSUE TITLE
Module crashes on load with Roland UVC-02 Device on Windows

### ISSUE THREAD

**Issue by herzogmedia** [bitfocus/companion-module-generic-midi#4] opened 2024-06-12 07:57 UTC
When starting the module in current companion (3.3.1), it crashes with the following log output:

```
system: ** Starting Connection from "C:\Program Files\Companion\resources\bundled-modules\generic-midi\main.js" **
system: ** Connection started **
Starting up module class: W
Sentry disabled
Module-host accepted registration
Available MIDI Inputs:  [ 'Roland UVC-02', 'BMT 1', 'BMT 2' ] 
	Selected MIDI Input:   Roland UVC-02
Available MIDI Outputs: [ 'Microsoft GS Wavetable Synth', 'Roland UVC-02', 'BMT 1', 'BMT 2' ] 
	Selected MIDI Output:  Microsoft GS Wavetable Synth

error: MidiInWinMM::openPort: error creating Windows MM MIDI input port.

error: Trace: Init failed: Error: Internal RtMidi error
    at C:\Program Files\Companion\resources\bundled-modules\generic-midi\main.js:1:366559
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async C:\Program Files\Companion\resources\bundled-modules\generic-midi\main.js:1:335601
error: Failed to init: Error: Internal RtMidi error Error: Internal RtMidi error
    at r.openPort (C:\Program Files\Companion\resources\bundled-modules\generic-midi\main.js:1:680)
    at new C (C:\Program Files\Companion\resources\bundled-modules\generic-midi\main.js:1:398154)
    at W.configUpdated (C:\Program Files\Companion\resources\bundled-modules\generic-midi\main.js:1:401178)
    at W.init (C:\Program Files\Companion\resources\bundled-modules\generic-midi\main.js:1:400507)
    at C:\Program Files\Companion\resources\bundled-modules\generic-midi\main.js:1:366495
    at C:\Program Files\Companion\resources\bundled-modules\generic-midi\main.js:1:335440
    at t.default._tryToStartAnother (C:\Program Files\Companion\resources\bundled-modules\generic-midi\main.js:1:334487)
    at C:\Program Files\Companion\resources\bundled-modules\generic-midi\main.js:1:335647
    at new Promise (<anonymous>)
    at t.default.add (C:\Program Files\Companion\resources\bundled-modules\generic-midi\main.js:1:335290)
system: ** Connection stopped **
```

Is this related to the WinMM-Library?

**Comment by MeestorX** [comment] 2024-06-12 13:41
I wonder if there's an issue with the Roland driver. If you choose a different MIDI input, does it still crash?

**Comment by herzogmedia** [comment] 2024-06-12 13:55
Where would I choose a MIDI port? It crashes before I get to the config screen. I'll later try to start the module with the roland disconnected and get back to you

**Comment by MeestorX** [comment] 2024-06-12 15:47
Yes, unplug the Roland and see what happens. If that fixes the issue then check and see if there's an updated drive for the Roland.

**Comment by herzogmedia** [comment] 2024-06-13 15:57
So this indeed fixes the issue. Unfortunately, there is no new driver for the Roland but now that the module loads properly, I can choose a different MIDI device in config and it then still loads after plugging the Roland back in

**Comment by herzogmedia** [comment] 2024-06-13 15:59
for the module it would be nice to be able to change the midi device and reload the module instead of it crashing completely

**Comment by MeestorX** [comment] 2024-06-13 16:16
Ok, just so I'm clear, if you have the Roland disconnected and load the module, it runs properly. Then, you connect the Roland, and if you select it in the Module's config, does it again crash the module?
You're right, the module should try and recover from an error like that if possible.
Does this Roland interface work with other software properly? I think that a bug report should be made for RtMidi, as it is the one actually crashing. They may just say though that since WinMM (A Microsoft library) is the one with the error that it cannot be fixed and would require a fix from Roland. Lots of finger pointing I expect, or more likely, no response at all from Roland...

**Comment by MeestorX** [comment] 2024-06-13 16:22
I'll create a bug report for rtMidi, maybe you can fill in your Windows info and/or send a bug report to Roland too?
https://github.com/thestk/rtmidi/issues/339

**Comment by herzogmedia** [comment] 2024-06-13 17:21
> Ok, just so I'm clear, if you have the Roland disconnected and load the module, it runs properly. 

Yes.

> Then, you connect the Roland, and if you select it in the Module's config, does it again crash the module?

Not directly. If I select it in config and save, nothing happens. If I restart the module (or companion) with the Roland selected, it crashes again.

> Does this Roland interface work with other software properly? 

That is hard to say, since Roland does not mention MIDI at all in their documentation. After some digging and testing, I found out that they seem to use MIDI to communicate between their desktop software and the device. So the errors come from the device already beeing used by another application.

**Comment by MeestorX** [comment] 2024-06-13 17:27
I had assumed it was a USB to MIDI adapter, but it's a MIDI device. Good chance it's not a "general MIDI-type" device and is a proprietary device for Roland software only.
If it doesn't work with other MIDI software, then there's no reason to think it should work with my module.
But... You're not wrong about the crashing, it would be good to NOT have that happen - have it simply not work instead of crashing.

**Comment by herzogmedia** [comment] 2024-06-13 18:18
> If it doesn't work with other MIDI software, then there's no reason to think it should work with my module.

I totally agree. And I do not expect it to. My bug report was more about the fact, that it crashes before letting me choose a different device.

**Comment by MeestorX** [comment] 2024-06-13 18:44
I added some error handling to the module, you can download it here:
https://discourse.checkcheckonetwo.com/t/v3-rcp-module-installation-instructions/3458
If you don't have an account, create one and send me a dm so I can raise your trust level so you can download. Alternately, you can send me a DM there with your e-mail address and I can send you a link. Would appreciate it if you could test it as I don't have a "bad" device to try it with...

**Comment by MarekPro1** [comment] 2024-07-08 15:28
Hello I have the same issue but  I am not using Roland drivers indeed I am using BOME network app, but even when I close the app it crashes the same. I am on windows newest beta wersion, midi connections ready. But it crashes.

ystem: ** Log cleared **
system: ** Starting Connection from "C:\Program Files\Companion\resources\bundled-modules\generic-midi\main.js" **
system: ** Connection started **
Starting up module class: W
Sentry disabled
Module-host accepted registration
Available MIDI Inputs:  [ 'Ableton-FOH' ] 
	Selected MIDI Input:   Ableton-FOH
Available MIDI Outputs: [ 'Microsoft GS Wavetable Synth', 'Ableton-FOH' ] 
	Selected MIDI Output:  Microsoft GS Wavetable Synth


error: 
MidiOutWinMM::openPort: error creating Windows MM MIDI output port.

error: Trace: Init failed: Error: Internal RtMidi error
    at C:\Program Files\Companion\resources\bundled-modules\generic-midi\main.js:1:366559
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async C:\Program Files\Companion\resources\bundled-modules\generic-midi\main.js:1:335601
error: Failed to init: Error: Internal RtMidi error Error: Internal RtMidi error
    at a.openPort (C:\Program Files\Companion\resources\bundled-modules\generic-midi\main.js:1:1052)
    at new y (C:\Program Files\Companion\resources\bundled-modules\generic-midi\main.js:1:399085)
    at W.configUpdated (C:\Program Files\Companion\resources\bundled-modules\generic-midi\main.js:1:401231)
    at W.init (C:\Program Files\Companion\resources\bundled-modules\generic-midi\main.js:1:400507)
    at C:\Program Files\Companion\resources\bundled-modules\generic-midi\main.js:1:366495
    at C:\Program Files\Companion\resources\bundled-modules\generic-midi\main.js:1:335440
    at t.default._tryToStartAnother (C:\Program Files\Companion\resources\bundled-modules\generic-midi\main.js:1:334487)
    at C:\Program Files\Companion\resources\bundled-modules\generic-midi\main.js:1:335647
    at new Promise (<anonymous>)
    at t.default.add (C:\Program Files\Companion\resources\bundled-modules\generic-midi\main.js:1:335290)

**Comment by MeestorX** [comment] 2024-07-08 18:20
Thank you for letting me know. 
Can you confirm what version of the generic-MIDI module you're running? (Click on the ? beside the module name)

**Comment by MarekPro1** [comment] 2024-07-08 18:37
Hello 1.1.7
![image](https://github.com/bitfocus/companion-module-generic-midi/assets/110824876/780db8d9-66b9-4e6e-9f27-c606da4d49b5)

**Comment by MeestorX** [comment] 2024-07-08 18:48
Copy that. If you are able, please try 1.1.8 and let me know if that fixes the problem.
https://discourse.checkcheckonetwo.com/t/companion-v3-x-x-modules-for-yamaha-and-the-new-generic-midi-module

**Comment by MarekPro1** [comment] 2024-07-08 18:50
Yes I can test it, but still after the years I don't know how to upgrade plugins in companion :(

**Comment by MarekPro1** [comment] 2024-07-08 18:52
I didn't log in.

**Comment by MeestorX** [comment] 2024-07-08 18:53
No problem. The instructions on how to run the versions on my site are at the link above. You will have to register to download though.

**Comment by MarekPro1** [comment] 2024-07-08 18:57
Ok Iam going on it.

**Comment by MeestorX** [comment] 2024-07-08 19:37
Did you click on the "see here" link? ;-)

Let me know your username and I'll upgrade you manually.

**Comment by MarekPro1** [comment] 2024-07-08 19:51
Yes in the first picture. my username is: Marekpro

**Comment by MeestorX** [comment] 2024-07-08 20:53
Ok, you should be good now.

**Comment by MarekPro1** [comment] 2024-07-09 07:25
Hello, I got the new version 1.1.8 but it does the same. 
![image](https://github.com/bitfocus/companion-module-generic-midi/assets/110824876/f3e60429-c4a9-4f7c-92c8-56f2d7c86a19)


` Starting up module class: ModuleInstance
Sentry disabled
Module-host accepted registration
Available MIDI Inputs:  [ 'Ableton-FOH' ] 
	Selected MIDI Input:   Ableton-FOH
Available MIDI Outputs: [ 'Microsoft GS Wavetable Synth', 'Ableton-FOH' ] 
	Selected MIDI Output:  Microsoft GS Wavetable Synth


error: 
MidiOutWinMM::openPort: error creating Windows MM MIDI output port.

error: Trace: Init failed: Error: Internal RtMidi error
    at eval (webpack://generic-midi/./node_modules/@companion-module/base/dist/module-api/base.js?:117:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async run (webpack://generic-midi/./node_modules/p-queue/dist/index.js?:163:29)
error: Failed to init: Error: Internal RtMidi error Error: Internal RtMidi error
    at Output.openPort (webpack://generic-midi/./node_modules/@julusian/midi/midi.js?:69:24)
    at new Output (webpack://generic-midi/./dist/midi/midi.js?:104:34)
    at ModuleInstance.configUpdated (webpack://generic-midi/./dist/main.js?:60:27)
    at ModuleInstance.init (webpack://generic-midi/./dist/main.js?:37:20)
    at eval (webpack://generic-midi/./node_modules/@companion-module/base/dist/module-api/base.js?:113:28)
    at run (webpack://generic-midi/./node_modules/p-queue/dist/index.js?:157:104)
    at PQueue._tryToStartAnother (webpack://generic-midi/./node_modules/p-queue/dist/index.js?:105:17)
    at eval (webpack://generic-midi/./node_modules/p-queue/dist/index.js?:171:18)
    at new Promise (<anonymous>)
    at PQueue.add (webpack://generic-midi/./node_modules/p-queue/dist/index.js?:152:16)
system: ** Connection stopped ** `

**Comment by MeestorX** [comment] 2024-07-09 13:50
@Julusian - What's the best way to handle an error like this from RtMidi when trying to open a bad port?
This doesn't seem to be doing it.
https://github.com/bitfocus/companion-module-generic-midi/blob/e73ea37488dfc081ea67dec852292c7213270d73/src/midi/midi.ts#L29-L33

I basically just want the module to ignore bad ports and not crash the module.

**Comment by Julusian** [comment] 2024-07-14 20:23
@MeestorX  I see no reason why that catch wouldn't work. The error is definitely being thrown as a js exception, so would be caught by that.

I think you forgot to do a `yarn build` to compile the typescript before building the module. Looking at the compiled code of the module (freshly downloaded from your website), it looks like this:
![image](https://github.com/user-attachments/assets/10b5adcb-66ce-48ab-9858-12340b57ee45)
It's a mess (because of webpack), but notice that there isn't a try/catch around it.

**Comment by MeestorX** [comment] 2024-07-14 21:05
Oh! I didn't know about `yarn build`. I don't ever remember executing that command. The "watcher" that restarts companion when you make changes while running in dev mode doesn't automagically run that command?

**Comment by Julusian** [comment] 2024-07-14 21:30
running `yarn dev` in this repository would. but no companion won't do that for you as it doesn't know about converting module typescript to javascript.

I am wondering if perhaps the `yarn companion-module-build` command should be made to do typescript transpilation automatically, but that will require some thought on how to tell it to do so. it currently uses the same entrypoint js file as companion does, but this would mean they would need different values

**Comment by MeestorX** [comment] 2024-07-14 21:32
Copy that. No problem. I'll just have to remember that extra step from now on with TS modules.

**Comment by MeestorX** [comment] 2024-07-14 21:34
It's been rebuilt now and hopefully should fix the problem for you, @herzogmedia and @MarekPro1.
LMK!

**Comment by MeestorX** [comment] 2024-07-19 19:22
Are either of you able to try this? I don't have a bad MIDI device with which to test it.
@herzogmedia @MarekPro1

**Comment by MarekPro1** [comment] 2024-07-19 20:51
I can test it next week. soonest

**Comment by MeestorX** [comment] 2024-08-16 17:56
Has anyone had a chance to test this yet?

**Comment by MarekPro1** [comment] 2024-08-26 12:43
> Has anyone had a chance to test this yet?

I am going to.

**Comment by MeestorX** [comment] 2024-09-09 18:04
I'm going to close this issue as I assume the problem is no longer there.

**Closed as completed by MeestorX** 2024-09-09 18:04 UTC
